---
title: "RTD Example: ggthemes"
author: "Villanova DS2 student"
format:
  html: default
  pdf: default
---

```{r set up}
library(dplyr)
library(tidyverse)
library(gridExtra)
library(ggplot2)
library(ggthemes)


# Additional Content by MP
centertitles <- theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5))

# ggplot() +
#   ???? +
#   centertitles

```

```{r ggplot graphs}
ggplot(USArrests, aes(x = Murder, y = Assault)) +
    geom_point() +
    labs(x = "Murder Rate",
         y = "Assault Rate",
         title = "U.S. State Murder Rate vs Assault Rates")

mtcars %>%
    ggplot(aes(x = mpg, y = wt, color = as.factor(cyl))) +
    geom_point() +
    labs(x = "Miles Per Gallon",
         y = "Weight (lbs / 1000)",
         color = "Number of Cylinders",
         title = "Automobile Weight vs MPG by Engine Cylinders") 

mtcars %>%
    ggplot(aes(factor(cyl), mpg)) +
    geom_boxplot()
```

```{r Themes}
# ggthemes Graphs
ggplot(USArrests, aes(x = Murder, y = Assault)) +
    geom_point() +
    theme_few() +
    ggtitle("theme_few()")

ggplot(USArrests, aes(x = Murder, y = Assault)) +
    geom_point() +
    theme_clean() +
    ggtitle("theme_clean()")

ggplot(USArrests, aes(x = Murder, y = Assault)) +
    geom_point() +
    theme_gdocs()+
    ggtitle("theme_gdocs()")

ggplot(USArrests, aes(x = Murder, y = Assault)) +
    geom_point() +
    theme_economist()+
    ggtitle("theme_econimist()")

ggplot(USArrests, aes(x = Murder, y = Assault)) +
    geom_point() +
    theme_wsj()+
    ggtitle("theme_wsj()")

ggplot(USArrests, aes(x = Murder, y = Assault)) +
    geom_point() +
    theme_map()+
    ggtitle("theme_map()")

# Using ggplot2 to recreate theme_few()
ggplot(USArrests, aes(x = Murder, y = Assault)) +
    geom_point()+
    theme_bw() +
    theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
        ) +
    labs(x = "Murder Rate",
         y = "Assault Rate",
         title = "U.S. State Murder Rate vs Assault Rates")
```

```{r Scales, fig.height = 9}
# ggthemes Graphs
mtcars %>%
    ggplot(aes(x = mpg, y = wt, color = as.factor(cyl))) +
    geom_point() +
    ggtitle("scale_color_few") +
    labs(x = "Miles Per Gallon",
         y = "Weight (lbs / 1000)",
         color = "Number of Cylinders") +
    scale_colour_few()

WSJ <- mtcars %>%
    ggplot(aes(x = mpg, y = wt, color = as.factor(cyl))) +
    geom_point() +
     labs(title = "WSJ Theme and Scale",
          x = "Miles Per Gallon",
          y = "Weight (lbs / 1000)",
          color = "Number of Cylinders") +
    theme_wsj() +
    scale_color_wsj() 

# Using ggplot2 to recreate WSJ graph
WSJ_remake <- mtcars %>%
    ggplot(aes(x = mpg, y = wt, color = as.factor(cyl))) +
    geom_point() +
    labs(y = "Weight (lbs / 1000)",
         title = "WSJ Remake") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5, 
                                    face = "bold", 
                                    size = 12),
          axis.title.x = element_blank(),
          legend.title = element_blank(),
          axis.title.y = element_text(angle = 0, 
                                      vjust = 0.5),
          panel.grid.minor = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.border = element_blank()) +
    scale_color_manual(values = c("dark red","blue","tan"))

grid.arrange(WSJ, WSJ_remake)

```




```{r Geoms}
# ggplot Graph
mtcars %>%
    ggplot(aes(factor(cyl), mpg)) +
    geom_boxplot()

# ggthemes Graph
mtcars %>%
    ggplot(aes(factor(cyl), mpg)) +
    ggtitle("geom_tufteboxplot()") +
    labs(x = "Number of Cylinders",
         y = "Miles Per Gallon") +
    geom_tufteboxplot() 
```

