---
title: "Mini-Project 1: Maps"
format:
  html: default
---
  
```{r}
#| include: false

library(tidyverse)
```

### Overview

You will produce choropleth maps illustrating two different characteristics -- one numeric and one categorical -- that have been measured for each US state (you can choose to exclude Alaska and Hawaii), like we did in the "Creating Informative Maps" activity.  Just as we found state-level data from both a vaccine data set and the `poliscidata` package, you should find *your own* state-level data that is interesting to you.  

A few additional details for this mini-project:

1. You should create *two* versions of each plot -- one that is static and one that is interactive.

2. Be sure to include a note on your plots with your data source.

3. You should be able to merge your state-level data with the state mapping data sets we used in class.

4. Be sure you label your plot well *and* provide a description of what insights can be gained from each *static* plot.  For one of your static plots, this should be in the form of alt-text, using the "Four Ingredient Model" in the article from class.

5. Check out this [rubric](https://drive.google.com/file/d/1AL6Gc960i06CY0ZG-1hPyEtJseDrsF6u/view?usp=sharing) for Mini-Project 1.


### Submission and Timeline

Mini-Project 1 must be submitted on Moodle by **11:00 PM on Fri Feb 21**.  You should submit your two static plots, along with descriptions and alt-text, in a pdf document.  For your interactive plots, just submit a GitHub link where I can see your code that would produce a nice html document.  Then, in Mini-Project 2, I will ask you to build a webpage where you will link to these interactive html pages.

